---
- name: Setup Apache Webserver
  hosts: clientnode
  become: true
  become_user: root
  tasks:
    - name: Install HTTPD package
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: Start HTTPD service
      ansible.builtin.service:
        name: httpd
        state: started
    - name: Enable HTTPD service
      ansible.builtin.service:
        name: httpd
        enabled: yes
    - name: Copy index.html file
      ansible.builtin.copy:
        src: "/home/ec2-user/labs/index.html"
        dest: "/var/www/html/index.html"
        owner: ec2-user
        group: ec2-user
        mode: "0644"
    - name: Restart the HTTPD Service
      ansible.builtin.service:
        name: httpd
        state: restarted
